# this is called a play, a playbook can have multiple plays
# the play can includes the vars section to contains the variables for the play
- name: Configure webserver with nginx
  hosts: webservers
  sudo: true
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: dest=/etc/nginx/sites-enabled/default src=/etc/nginx/sites-available/default state=link    

    - name: copy index file
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
